name = "aniri-prod"
account_id = "1bb75723604137a1707a9b97801a92e5"
main = "_worker.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "aniri.tymelinestudios.com/*", zone_name = "tymelinestudios.com" }
]
